name: ExtendedHorizons
version: ${version}
main: me.mapacheee.extendedhorizons.ExtendedHorizonsPlugin
api-version: '1.21'
folia-supported: true
description: ${description}
author: Mapacheee
website: https://github.com/mapacheee/extendedhorizons
depend: [ MapacheeeLib ]
softdepend: [ WorldEdit, FastAsyncWorldEdit, PlaceholderAPI ]

commands:
  extendedhorizons:
    description: Main ExtendedHorizons command
    usage: /<command>
    aliases: [ eh ]
    permission: extendedhorizons.use

permissions:
  extendedhorizons.use:
    description: Basic permission to use ExtendedHorizons
    default: true

